name: Check Markdown links

on: 
    push:
        branches:
            - master
    schedule:
        # Every Monday at 00:00 UTC
        - cron: "0 0 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1